### ISSUE TITLE
Compact version of `above`

### ISSUE THREAD

**Issue by emilaxelsson** [valderman/haste-deck#2]
Can I have a version of `above` where each row only uses as much vertical space as it needs?

Right now, if I say

```
oneLineOfText `above` bigPicture
```

the picture only gets the lower half of the slide.

**Comment by emilaxelsson** [comment]
I realized that I can do something like:

```
column $ reverse
    [ oneLineOfTest
    , bigPicture
    , ""
    , ""
    , ""
    , ""
    ]
```

But it would be good if the spacing could sort itself out automatically.

BTW, `column` seems to read the list in the wrong order.

**Comment by valderman** [comment]
Now there's a `sized` function which lets subslides essentially make size requests. For instance, if you want to have a heading above an image which is supposed to dominate the slide, you could say:

```
slide = heading `above` 0.8 `sized` image
```

...which will give 20% of the available vertical space to the heading and 80% to the image.

**Comment by emilaxelsson** [comment]
Thanks!

But it seems like whenever I do `sized s $ centered ...` the whole presentation just goes blank.

And the same happens with `group $ centered ...`.

**Comment by valderman** [comment]
Yep, that's the Haste optimizer bug I was talking about. :) I'll probably have 0.5.2 out before the end of the day, where that should be fixed.

**Comment by valderman** [comment]
By the way, it's fixed on GitHub if you're feeling impatient.
